services:
  - type: web
    name: cop-ibe
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: SQLITE_PATH
        value: /var/data/simple_church.db
    disk:
      name: cop-ibe-data
      mountPath: /var/data
      sizeGB: 1
